# Generated by Django 2.1.5 on 2019-02-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190210_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
